services:
  prometheus:
    image: docker.arvancloud.ir/prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring    

  grafana:
    image: docker.arvancloud.ir/grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  
    depends_on:
      - prometheus
    networks:
      - monitoring    

  node-exporter:
    image: docker.arvancloud.ir/prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    deploy:
      mode: global
    networks:
      - monitoring    
    volumes:
      - /:/host:ro    

  alertmanager:
    image: docker.arvancloud.ir/prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - monitoring

networks:
  monitoring:
    external: true
    name: monitoring  

