services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - prometheus   

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  
    depends_on:
      - prometheus
    networks:
      - prometheus    
    volumes:
      - ./grafana:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    deploy:
      mode: global
    networks:
      - prometheus    
    volumes:
      - /:/host:ro    

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - prometheus
    volumes:
      - ./alertmanager:/etc/alertmanager    

networks:
  prometheus:
    external: true
    name: prometheus  

