groups:
  - name: resource_alerts
    rules:
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes{instance="91.228.186.49:9100", job="node_exporter"} / node_memory_MemTotal_bytes{instance="91.228.186.49:9100", job="node_exporter"})) * 100 > 30
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High Memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 40% (current value: {{ $value }}%)"

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes{device="/dev/vda1", fstype="ext4", job="node_exporter", mountpoint="/host"} - node_filesystem_free_bytes{device="/dev/vda1", fstype="ext4" ,job="node_exporter", mountpoint="/host"}/node_filesystem_size_bytes{device="/dev/vda1", fstype="ext4", job="node_exporter", mountpoint="/host"})* 100 > 60
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High Disk usage on {{ $labels.instance }}"
          description: "Disk usage is above 60% (current value: {{ $value }}%)"


      - alert: HighSysLoad
        expr: (scalar(node_load1{job="node_exporter"}) * 100 / count(count(node_cpu_seconds_total{job="node_exporter"}) by (cpu))) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High SysLoad on {{ $labels.instance }}"
          description: "SysLoad is above 1% (current value: {{ $value }}% "


      - alert: HighCpuUsage
        expr: (100 * (1 - avg(rate(node_cpu_seconds_total{mode="idle", job="node_exporter"}[1m])) by (instance))) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High CPU Usage on {{ $labels.instance }}"
          description: "CPU Usage is above 1% (current value: {{ $value }}% "
