global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - "37.152.178.189:9100"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alert_rules.yml"

